name: 28591_test

#Proženje akcije ob vsakem potisku na glavno vejo main
on:
  push:
    branches: [main]

jobs:
  check-tests:
    name: Check for test scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  #Prenos vsebine repozitorija

      - name: Verify test scripts exist
        run: |
          # Preverimo, če obstaja testna skripta
          if [ ! -f ./tests/run_tests.sh ]; then
            echo "Testna skripta ni najdena!" >&2  # Zapis napake v standardni izhod
            exit 1  # Zaključimo z napako
          fi

      - name: Upload error log if exists
        if: failure()  #Izvede se le, če je prejšnji korak SPODLETEL
        run: echo "Testna skripta ni najdena!" > napaka.txt  #Zapišem napako v datoteko

      - name: Upload napaka.txt
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: napaka
          path: napaka.txt  #"Artefakt", ki ga bo naslednji posel lahko prenesel

  run-tests:
    name: Run tests
    needs: check-tests  #Ta posel se izvede šele, ko je "check-tests" USPEŠNO končan
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  #Matrika za izvajanje na več operacijskih sistemih -tu bi ga pac dodal not samo ne dela pol skripta

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  #Prenos kode

      - name: Download napaka.txt
        uses: actions/download-artifact@v4
        with:
          name: napaka
        continue-on-error: true  #Če "artefakt" ne obstaja (ni bilo napake), nadaljujem brez težav

      - name: Check for errors
        run: |
          if [ -f napaka/napaka.txt ]; then 
            echo "Napaka pri prejšnjem \"jobu\":"
            cat napaka/napaka.txt
            exit 1
          fi

      - name: Set execute permission for test script
        if: runner.os == 'Linux'  #Pravice za izvajanje samo na Linuxu
        run: chmod +x ./tests/run_tests.sh

      - name: Run tests
        run: ./tests/run_tests.sh  #Izvedem testno skripto
